name: CI_CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Load Github Config
        run: |
          echo 'CLIENT_ID=${{ secrets.CLIENT_ID }}' >> config/.env.dev
          echo 'CLIENT_SECRET=${{ secrets.CLIENT_SECRET }}' >> config/.env.dev
      - name: Build && Deploy to netlify (for Design QA)
        run: npm run publish:netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        # working-directory: dist
